name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/frontend-project

            git fetch origin
            git reset --hard origin/main

            cd emp-management-api
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache

            cd ../emp-management
            pnpm install --frozen-lockfile
            pnpm build

            sudo systemctl reload nginx